### ISSUE TITLE
与nuxt对比的优缺点

### ISSUE THREAD

**Issue by zhangyuang** [vapperjs/vapperjs.org#4]
希望能出一个章节阐述一下与nuxt.js的不同之处以及优缺点

**Comment by HcySunYang** [comment]
In fact, we deliberately avoided comparing with any existing frameworks. We explicitly showed the features of Vapper here https://vapperjs.org/introduction.html#necessary-webpack-configuration, which I think is enough for the user to identify which framework to use. But for Chinese users, there is also an article here https://zhuanlan.zhihu.com/p/86246776.
